# Generated by Django 5.0.6 on 2026-08-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0015_documento_de_ejemplo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje', 'Mensaje en una Sesión'), ('tarea', 'Tarea'), ('agente', 'Trabajo de un agente')], default='mensaje', max_length=16)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('enlace', models.CharField(blank=True, max_length=300)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'leida'], name='notificacio_user_id_99de6e_idx')],
            },
        ),
    ]
