# Generated by Django 5.0.6 on 2026-06-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='grid_h',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='document',
            name='grid_w',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='document',
            name='grid_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='grid_y',
            field=models.IntegerField(default=0),
        ),
    ]
