# Generated by Django 5.0.6 on 2026-06-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_document_grid_h_document_grid_w_document_grid_x_and_more'),
        ('organizations', '0004_systemconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='area',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='agents', to='organizations.systemconnection'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='erp_type',
            field=models.CharField(blank=True, choices=[('odoo', 'Odoo'), ('sap_b1', 'SAP Business One')], default='odoo', max_length=20),
        ),
    ]
