# Generated by Django 5.0.6 on 2026-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_area_agent_instructions_agent_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('accent', models.CharField(blank=True, max_length=9)),
                ('flow', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_templates',
                'ordering': ['-is_featured', '-uses_count', 'name'],
            },
        ),
    ]
