# Generated by Django 5.0.6 on 2026-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttemplate',
            name='kind',
            field=models.CharField(choices=[('community', 'Comunidad'), ('role', 'Rol')], default='community', max_length=12),
        ),
    ]
