# Generated by Django 5.0.6 on 2026-07-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_automation_routine'),
        ('organizations', '0007_contextcubicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='organizations.systemconnection'),
        ),
        migrations.AddField(
            model_name='automation',
            name='event_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automation',
            name='event_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automation',
            name='event_type',
            field=models.CharField(blank=True, choices=[('new_table', 'Nueva tabla o base de datos'), ('new_rows', 'Nuevas filas en una tabla'), ('connection_down', 'Conexión caída')], max_length=30),
        ),
        migrations.AddField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('interval', 'Programado'), ('event', 'Por evento')], default='interval', max_length=20),
        ),
        migrations.AlterField(
            model_name='automation',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
