# Generated by Django 5.0.6 on 2026-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_automation_connection_automation_event_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
