# Generated by Django 5.0.6 on 2026-07-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_message_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='recommended_frequency',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools_summary',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='agenttemplate',
            name='recommended_frequency',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='agenttemplate',
            name='tools_summary',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
