# Generated by Django 5.0.6 on 2026-08-01 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_recommended_frequency_agent_tools_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Quien lo creó. Vacío = agente que vino con Afable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AgentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'agent_favorites',
            },
        ),
        migrations.AddConstraint(
            model_name='agentfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'agent'), name='un_favorito_por_usuario_y_agente'),
        ),
    ]
