# Generated by Django 5.0.6 on 2026-08-02 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agent_created_by_agentfavorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.TextField(blank=True, help_text='Qué datos específicos de la empresa puede consultar.')),
                ('reglas', models.TextField(blank=True, help_text='Qué debe y qué no debe hacer al responder.')),
                ('info_util', models.TextField(blank=True, help_text='Información de la empresa que le sirve y no está en ningún sistema.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='agents.agent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_de_agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de agente',
                'verbose_name_plural': 'Configuraciones de agente',
                'db_table': 'agent_configs',
            },
        ),
    ]
