# Generated by Django 5.0.6 on 2026-08-02 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentconfig'),
        ('organizations', '0009_companydocument_external_id_companydocument_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='handle',
            field=models.SlugField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='agents.agent'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('handle', ''), _negated=True), fields=('organization', 'handle'), name='unico_handle_de_agente_por_empresa'),
        ),
    ]
