# Generated by Django 5.0.6 on 2026-08-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_skill_skill_unico_nombre_de_habilidad_por_empresa'),
        ('workspaces', '0005_space_space_unico_slug_de_espacio_por_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='workspaces.space'),
        ),
    ]
