# Generated by Django 5.0.6 on 2026-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_conversation_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"dias": [0,1,2,3,4], "hora": 8, "minuto": 0}. Sin días = todos los días.'),
        ),
        migrations.AddField(
            model_name='automation',
            name='webhook_last_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automation',
            name='webhook_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('interval', 'Cada tanto'), ('schedule', 'A una hora fija'), ('webhook', 'Cuando avisa otro sistema'), ('event', 'Por evento')], default='interval', max_length=20),
        ),
    ]
