# Generated by Django 5.0.6 on 2026-08-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_quien_escribio_el_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fuentes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
