# Generated by Django 5.0.6 on 2026-08-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_fuentes_de_la_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='artefactos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
