# Generated by Django 5.0.6 on 2026-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0024_message_artefactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='accent',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='agent',
            name='icon',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
