# Generated by Django 5.0.6 on 2026-08-31 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_agent_accent_agent_icon'),
        ('archivos', '0003_permiso_de_todo_el_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='carpeta',
            field=models.ForeignKey(blank=True, help_text='La carpeta de la que cuelga. Su contenido es el alcance del agente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes', to='archivos.carpeta'),
        ),
    ]
