# Generated by Django 5.0.6 on 2026-08-31 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_permiso_de_todo_el_workspace'),
        ('organizations', '0015_documento_de_ejemplo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='personal',
            field=models.BooleanField(default=False, help_text='La carpeta privada de una persona, no una carpeta de la empresa.'),
        ),
        migrations.CreateModel(
            name='SolicitudDePublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, help_text='Qué es esto y por qué le sirve al resto, en una línea.', max_length=300)),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando respuesta'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('respuesta', models.CharField(blank=True, help_text='Por qué se rechazó. Vacío en las aprobadas.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_propuestas', to='archivos.carpeta')),
                ('destino_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_recibidas', to='archivos.carpeta')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_de_publicacion', to='organizations.companydocument')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_pedidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de publicación',
                'verbose_name_plural': 'Solicitudes de publicación',
                'db_table': 'archivos_solicitudes_de_publicacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='solicituddepublicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('document',), name='una_solicitud_abierta_por_documento'),
        ),
    ]
