# Generated by Django 5.0.6 on 2026-06-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='response_style',
            field=models.CharField(choices=[('ejecutivo', 'Ejecutivo — resumido, bullet points'), ('analitico', 'Analítico — detallado con cifras'), ('tecnico', 'Técnico — con terminología especializada')], default='ejecutivo', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
