# Generated by Django 5.0.6 on 2026-06-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_objectives_user_response_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
