# Generated by Django 5.0.6 on 2026-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usercontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
