# Generated by Django 5.0.6 on 2026-07-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_google_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org_admin',
        ),
    ]
