# Generated by Django 5.0.6 on 2026-08-07 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0014_empresa_es_el_nivel_de_arriba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('atendido', 'Atendido')], default='nuevo', max_length=12)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_soporte', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_soporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje a soporte',
                'verbose_name_plural': 'Mensajes a soporte',
                'db_table': 'mensajes_soporte',
                'ordering': ['-creado_at'],
            },
        ),
    ]
