# Generated by Django 5.0.6 on 2026-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('segment', models.CharField(choices=[('custom', 'Custom — requiere análisis/automatización a medida'), ('saas', 'SaaS — autoatención')], default='custom', max_length=16)),
                ('summary', models.TextField(help_text='Qué quiere implementar/automatizar (redactado por la IA).')),
                ('transcript', models.JSONField(blank=True, default=list, help_text='Conversación completa.')),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
