# Generated by Django 5.0.6 on 2026-07-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('workflow', 'Workflow — automatización a medida con n8n'), ('saas', 'Plataforma — autoatención')], default='workflow', max_length=16),
        ),
        migrations.AlterField(
            model_name='lead',
            name='summary',
            field=models.TextField(help_text='Qué flujo quiere automatizar (redactado por la IA).'),
        ),
    ]
