# Generated by Django 5.0.6 on 2026-08-01 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_companydocument_external_id_companydocument_source_and_more'),
        ('workspaces', '0002_workspace_para_usuarios_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='employees',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='tax_id',
            field=models.CharField(blank=True, help_text='RUT / NIF.', max_length=30),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='sector',
            field=models.CharField(blank=True, choices=[('manufactura', 'Manufactura'), ('tecnologia', 'Tecnología / Software'), ('retail', 'Retail / Comercio'), ('servicios', 'Servicios profesionales'), ('alimentos', 'Alimentos y bebidas'), ('construccion', 'Construcción'), ('logistica', 'Logística / Transporte'), ('energia', 'Energía'), ('turismo', 'Turismo / Hospitalidad'), ('otro', 'Otro')], max_length=120),
        ),
    ]
