# Generated by Django 5.0.6 on 2026-08-02 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentconfig'),
        ('organizations', '0009_companydocument_external_id_companydocument_source_and_more'),
        ('workspaces', '0004_enlazar_workspaces_con_su_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji de la tarjeta.', max_length=8)),
                ('visibility', models.CharField(choices=[('abierto', 'Abierto — lo ve todo el Workspace'), ('restringido', 'Restringido — solo quienes se agreguen')], default='abierto', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='spaces', to='agents.agent')),
                ('connections', models.ManyToManyField(blank=True, related_name='spaces', to='organizations.systemconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='spaces', to='organizations.companydocument')),
                ('members', models.ManyToManyField(blank=True, related_name='spaces', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'workspace_spaces',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unico_slug_de_espacio_por_workspace'),
        ),
    ]
