# Generated by Django 5.0.6 on 2026-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Correo para comprobantes de pago.', max_length=254),
        ),
    ]
