# Generated by Django 5.0.6 on 2026-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onboarding_oculto',
            field=models.BooleanField(default=False),
        ),
    ]
