# Generated by Django 5.0.6 on 2026-08-07 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_la_conversacion_es_de_un_workspace'),
        ('organizations', '0014_empresa_es_el_nivel_de_arriba'),
        ('workspaces', '0012_el_espacio_pasa_a_llamarse_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='organizations.systemconnection'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='organizations.companydocument'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='visibility',
            field=models.CharField(choices=[('abierto', 'Abierto — entra toda la empresa'), ('restringido', 'Restringido — solo quienes se agreguen')], default='abierto', max_length=16),
        ),
    ]
