# Generated by Django 5.0.6 on 2026-08-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_los_related_name_del_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='documents',
        ),
    ]
