# Generated by Django 5.0.6 on 2026-08-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_documento_de_ejemplo'),
        ('payments', '0004_la_empresa_es_la_que_paga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_usuarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='tokens_por_mes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SaldoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos_comprados', models.BigIntegerField()),
                ('creditos_usados', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_adicionales', to='organizations.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Saldo adicional',
                'verbose_name_plural': 'Saldos adicionales',
                'db_table': 'saldos_adicionales',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarifaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('proveedor', models.CharField(max_length=20)),
                ('precio_entrada_usd_millon', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio_salida_usd_millon', models.DecimalField(decimal_places=4, max_digits=10)),
                ('vigente_desde', models.DateTimeField()),
                ('notas', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Tarifa de modelo',
                'verbose_name_plural': 'Tarifas de modelo',
                'db_table': 'tarifas_modelo',
                'ordering': ['modelo', '-vigente_desde'],
                'indexes': [models.Index(fields=['modelo', '-vigente_desde'], name='tarifas_mod_modelo_268d4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsumoTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=120)),
                ('motivo', models.CharField(blank=True, max_length=40)),
                ('tokens_entrada', models.IntegerField(default=0)),
                ('tokens_salida', models.IntegerField(default=0)),
                ('tokens_cache_lectura', models.IntegerField(default=0)),
                ('tokens_cache_escritura', models.IntegerField(default=0)),
                ('creditos', models.BigIntegerField(default=0)),
                ('sin_tarifa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='organizations.organization')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumo de tokens',
                'verbose_name_plural': 'Consumos de tokens',
                'db_table': 'consumo_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='consumo_tok_organiz_be312f_idx'), models.Index(fields=['modelo'], name='consumo_tok_modelo_39c6f7_idx')],
            },
        ),
    ]
