# Generated by Django 5.0.6 on 2026-08-19 22:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_medicion_de_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumotokens',
            name='tokens_cache_escritura_1h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumotokens',
            name='turno',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tarifamodelo',
            name='factor_cache_escritura',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.25'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tarifamodelo',
            name='factor_cache_escritura_1h',
            field=models.DecimalField(decimal_places=4, default=Decimal('2'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tarifamodelo',
            name='factor_cache_lectura',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1'), max_digits=6),
        ),
    ]
