# Generated by Django 5.0.6 on 2026-06-16 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_role', models.CharField(blank=True, max_length=255)),
                ('employees', models.CharField(blank=True, max_length=50)),
                ('rut', models.CharField(blank=True, max_length=30)),
                ('sector', models.CharField(blank=True, choices=[('manufactura', 'Manufactura'), ('tecnologia', 'Tecnología / Software'), ('retail', 'Retail / Comercio'), ('servicios', 'Servicios profesionales'), ('alimentos', 'Alimentos y bebidas'), ('construccion', 'Construcción'), ('logistica', 'Logística / Transporte'), ('energia', 'Energía'), ('turismo', 'Turismo / Hospitalidad'), ('otro', 'Otro')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('odoo_url', models.URLField(blank=True)),
                ('odoo_db', models.CharField(blank=True, max_length=255)),
                ('odoo_username', models.EmailField(blank=True, max_length=254)),
                ('odoo_api_key', models.CharField(blank=True, max_length=512)),
                ('odoo_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
