# Generated by Django 5.0.6 on 2026-06-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('system_type', models.CharField(choices=[('odoo', 'Odoo'), ('sap_b1', 'SAP B1'), ('hubspot', 'HubSpot'), ('shopify', 'Shopify')], max_length=20)),
                ('modules_found', models.JSONField(default=list)),
                ('ai_context', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='organizations.organization')),
            ],
            options={
                'db_table': 'integration_scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
