# Generated by Django 5.0.6 on 2026-06-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_activeintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(choices=[('odoo', 'Odoo'), ('mssql', 'SQL Server / SAP Business One'), ('postgresql', 'PostgreSQL'), ('csv', 'Excel / CSV')], max_length=50)),
                ('_config_encrypted', models.TextField(blank=True, db_column='config_encrypted')),
                ('schema_cache', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='organizations.organization')),
            ],
            options={
                'db_table': 'system_connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
