# Generated by Django 5.0.6 on 2026-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_systemconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconnection',
            name='category',
            field=models.CharField(choices=[('erp', 'ERP'), ('crm', 'CRM'), ('db', 'Base de datos'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
