# Generated by Django 5.0.6 on 2026-07-09 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_systemconnection_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('politica', 'Política'), ('manual', 'Manual'), ('catalogo', 'Catálogo'), ('financiero', 'Financiero'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('file', models.FileField(upload_to='company_documents/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('processing_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_description', models.TextField(blank=True)),
                ('products_services', models.TextField(blank=True)),
                ('target_customers', models.TextField(blank=True)),
                ('glossary', models.TextField(blank=True)),
                ('tone_guidelines', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_contexts',
            },
        ),
    ]
