# Generated by Django 5.0.6 on 2026-07-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_companydocument_organizationcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextCubicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_cubicles', to='organizations.organization')),
            ],
            options={
                'db_table': 'context_cubicles',
                'ordering': ['order', 'id'],
            },
        ),
    ]
