# Generated by Django 5.0.6 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_contextcubicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Privado (solo lo ve quien lo subió) o público (visible para toda la empresa).'),
        ),
    ]
