# Generated by Django 5.0.6 on 2026-07-22 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_companydocument_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='source',
            field=models.CharField(choices=[('manual', 'Subido manualmente'), ('drive_sync', 'Sincronizado desde Google Drive')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconnection',
            name='connector_type',
            field=models.CharField(choices=[('odoo', 'Odoo'), ('mssql', 'SQL Server / SAP Business One'), ('postgresql', 'PostgreSQL'), ('csv', 'Excel / CSV'), ('google_drive', 'Google Drive')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='companydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'external_id'), name='unique_org_external_id'),
        ),
    ]
