# Generated by Django 5.0.6 on 2026-08-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_empresa_es_el_nivel_de_arriba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='source',
            field=models.CharField(choices=[('manual', 'Subido manualmente'), ('drive_sync', 'Sincronizado desde Google Drive'), ('ejemplo', 'Datos de ejemplo')], default='manual', max_length=20),
        ),
    ]
